#  ✅ TG: https://t.me/QuantX
mixed-port: 7890
allow-lan: true
mode: rule
log-level: silent
ipv6: false
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  default-nameserver:
    - 114.114.114.114
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fallback:
    - 114.114.114.114
    - 223.5.5.5
proxy-providers:
#  ✅ 第一个订阅链接
  GB: &proxy
    type: http
    path: ./Proxies/proxy.yaml
    # 将Clash订阅链接 替换为你的Clash机场订阅链接（clash meta v1.11.2及以上内核支持通用订阅格式(V2ray URL形式)）
    url: Clash订阅链接 
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
#  ✅ 第二个订阅链接
  DY: &proxy
    type: http
    path: ./Proxies/DY.yaml
    # 将Clash订阅链接 替换为你的Clash机场订阅链接（clash meta v1.11.2及以上内核支持通用订阅格式(V2ray URL形式)）
    url: Clash订阅链接 
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
  HK:
    <<: *proxy
    filter: 港|🇭🇰|HK|(?i)Hong

  US:
    <<: *proxy
    filter: 美|🇺🇸|🇺🇲|US|(?i)States|American


proxy-groups:
  - name: 节点选择
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Proxy.png
    type: select
    proxies:
      - 香港节点
      - 美国节点
      - 白嫖订阅
      - 茶猫订阅      
      - DIRECT
  - name: 白嫖订阅
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Static.png
    type: url-test
    use:
      - GB
  - name: 茶猫订阅
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Static.png
    type: url-test
    use:
      - DY


  - name: 电报服务
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Netflix.png
    type: select
    proxies:
      - 香港节点
      - 美国节点
      - 白嫖订阅
      - 茶猫订阅      
      - DIRECT
  - name: 仓库服务
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Disney+.png
    type: select
    proxies:
      - 香港节点
      - 美国节点
      - 白嫖订阅
      - 茶猫订阅      
      - DIRECT
  - name: 声田服务
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/TikTok.png
    type: select
    proxies:
      - 香港节点
      - 美国节点
      - 白嫖订阅
      - 茶猫订阅      
      - DIRECT
  - name: 漏网之鱼
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Final.png
    type: select
    proxies:
      - DIRECT
      - 节点选择

  - name: 国内直连
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Direct.png
    type: select
    proxies:
      - DIRECT
      - 节点选择
 





  - name: 香港节点
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Hong_Kong.png
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 600
    tolerance: 50
    use:
      - HK

  - name: 美国节点
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/United_States.png
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 600
    tolerance: 50
    use:
      - US


rule-providers:
  Telegram:
    type: http
    behavior: classical
    path: ./RuleSet/Extra/Telegram/Telegram.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master//Clash/RuleSet/Extra/Telegram/Telegram.yaml
    interval: 86400

  Github:
    type: http
    behavior: classical
    path: ./Clash/Github/Github.yaml
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@release/rule/Clash/GitHub/GitHub.yaml"
    interval: 86400

  Spotify:
    type: http
    behavior: classical
    path: ./Clash/Spotify/Spotify.yaml
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@release/rule/Clash/Spotify/Spotify.yaml"
    interval: 86400


  Global:
    type: http
    behavior: classical
    path: ./RuleSet/Global.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Global.yaml
    interval: 86400

  Streaming:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/Streaming.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/StreamingMedia/Streaming.yaml
    interval: 86400


  China:
    type: http
    behavior: classical
    path: ./RuleSet/China.yaml
    url: https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/China.yaml
    interval: 86400

rules:
  - RULE-SET,Github,仓库服务
  - RULE-SET,Spotify,声田服务
  - RULE-SET,Global,节点选择
  - RULE-SET,Streaming,节点选择
  - RULE-SET,Telegram,电报服务
  - RULE-SET,China,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT
  - IP-CIDR,fe80::/10,DIRECT
  - IP-CIDR,119.28.28.28/32,DIRECT
  - IP-CIDR,182.254.116.0/24,DIRECT
  - GEOIP,CN,DIRECT

  - MATCH,漏网之鱼